/****** Script for SelectTopNRows command from SSMS  ******/
/****** This is auto-generated by SSMS *****/
SELECT TOP (1000) [EmployeeID]
      ,[FirstName]
      ,[LastName]
      ,[Age]
      ,[Gender]
  FROM [SQLTutorial].[dbo].[EmployeeDemographics]
