/****** Script for SelectTopNRows command from SSMS  ******/
/****** This is auto-generated by SSMS *****/
SELECT TOP (1000) [EmployeeID]
      ,[JobTitle]
      ,[Salary]
  FROM [SQLTutorial].[dbo].[EmployeeSalary]